"""
redfish/collectors/firmware.py
================================
Redfish resources consumed
---------------------------
- UpdateService -> FirmwareInventory (collection) -> FirmwareInventory/{id}
  Contains SoftwareIdentity resources for every firmware component:
  BIOS, BMC/iDRAC/iLO, NIC firmware, RAID firmware, drive firmware, PSU
  firmware, CPLD, etc.  Each resource has: Version, Status, Manufacturer,
  Name, SoftwareId (what it applies to), Updateable (bool), RelatedItem.
- UpdateService -> SoftwareInventory (host-side OS software; we collect it
  too for completeness but mark the location accordingly)

No sensor readings are generated by firmware (nothing to chart over time),
but the alert engine checks for firmware mismatch flags when available.
"""
from .common import component, collection_members
from database.models import ComponentCategory


def collect(client, server, topology):
    components = []
    seen = set()

    update_svc_uri = topology.get("update_service")
    if not update_svc_uri:
        return components, []

    svc = client.get(update_svc_uri)
    if not svc:
        return components, []

    for coll_key in ("FirmwareInventory", "SoftwareInventory"):
        coll_link = (svc.get(coll_key) or {}).get("@odata.id")
        if not coll_link:
            continue
        for item in collection_members(client, coll_link):
            uri = item.get("@odata.id")
            if not uri or uri in seen:
                continue
            seen.add(uri)
            name = item.get("Name") or item.get("Id") or "Firmware Component"
            # Derive a human-readable location from RelatedItem links
            related = item.get("RelatedItem", [])
            location = None
            if related and isinstance(related, list):
                loc_parts = []
                for r in related[:2]:
                    if isinstance(r, dict) and r.get("@odata.id"):
                        loc_parts.append(r["@odata.id"].split("/")[-1])
                if loc_parts:
                    location = ", ".join(loc_parts)

            components.append(component(
                ComponentCategory.FIRMWARE, uri, name, item, location=location,
            ))

    return components, []
