; ============================================================================
; NaviFix — Inno Setup Installer Script
; ============================================================================
; Build with:  iscc setup.iss
; Output:      dist\NaviFix-1.0.0-setup.exe
;
; Requirements:
;   - Inno Setup 6.3+  (https://jrsoftware.org/isinfo.php)
;   - PyInstaller-compiled binaries in build\ before running iscc
;     (run build.ps1 which does this automatically)
; ============================================================================

#define AppName      "NaviFix"
#define AppVersion   "1.0.0"
#define AppPublisher "Navigator Systems"
#define AppURL       "https://navigatorsystems.com/navifix"
#define AppExeName   "NaviFixApp.exe"
#define TrayExeName  "NaviFixTray.exe"
#define AppId        "{{A3F7B291-52C4-4D3E-9A1B-8F2C6D4E7301}"

[Setup]
AppId                    = {#AppId}
AppName                  = {#AppName}
AppVersion               = {#AppVersion}
AppPublisher             = {#AppPublisher}
AppPublisherURL          = {#AppURL}
AppSupportURL            = {#AppURL}
AppUpdatesURL            = {#AppURL}
DefaultDirName           = {autopf}\{#AppName}
DefaultGroupName         = {#AppName}
AllowNoIcons             = no
; Require administrator for Program Files install
PrivilegesRequired       = admin
PrivilegesRequiredOverridesAllowed = dialog
OutputDir                = dist
OutputBaseFilename       = NaviFix-{#AppVersion}-setup
; Icon files are generated by prepare_assets.py — build.ps1 runs this automatically.
; If missing, Inno Setup uses its own defaults (no crash).
#define AssetDir "assets"
#ifexist AssetDir + "\icon.ico"
SetupIconFile            = assets\icon.ico
UninstallDisplayIcon     = {app}\assets\icon.ico
#endif
#ifexist AssetDir + "\wizard_banner.bmp"
WizardImageFile          = assets\wizard_banner.bmp
#endif
#ifexist AssetDir + "\wizard_logo.bmp"
WizardSmallImageFile     = assets\wizard_logo.bmp
#endif
Compression              = lzma2/ultra64
SolidCompression         = yes
WizardStyle              = modern
; Windows 11 / Windows 10 64-bit requirement
MinVersion               = 10.0.19041
ArchitecturesAllowed     = x64
ArchitecturesInstallIn64BitMode = x64
UninstallDisplayName     = {#AppName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "autostart"; Description: "Start {#AppName} automatically when Windows starts"; GroupDescription: "Startup options:"; Flags: unchecked

[Files]
; ── Compiled executables (produced by build.ps1 / PyInstaller) ──────────────
Source: "build\NaviFixApp\NaviFixApp.exe";          DestDir: "{app}";          Flags: ignoreversion
Source: "build\NaviFixApp\*";                       DestDir: "{app}";          Flags: ignoreversion recursesubdirs createallsubdirs
Source: "build\NaviFixTray\NaviFixTray.exe";        DestDir: "{app}";          Flags: ignoreversion
Source: "build\NaviFixTray\*";                      DestDir: "{app}";          Flags: ignoreversion recursesubdirs createallsubdirs

; ── Splash screen and app assets ────────────────────────────────────────────
Source: "..\installer\app\splash.html";             DestDir: "{app}";          Flags: ignoreversion
Source: "assets\icon.ico";                          DestDir: "{app}\assets";   Flags: ignoreversion

; ── Docker Compose + Backend source ─────────────────────────────────────────
Source: "..\docker-compose.yml";                    DestDir: "{app}";          Flags: ignoreversion
Source: "..\backend\*";                             DestDir: "{app}\backend";  Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "*.pyc,__pycache__,venv,.git,instance"
Source: "..\backend\.env.example";                  DestDir: "{app}\backend";  Flags: ignoreversion

; ── PowerShell launcher scripts ─────────────────────────────────────────────
Source: "..\installer\launcher\start.ps1";          DestDir: "{app}\launcher"; Flags: ignoreversion
Source: "..\installer\launcher\stop.ps1";           DestDir: "{app}\launcher"; Flags: ignoreversion
Source: "..\installer\launcher\first_run.ps1";      DestDir: "{app}\launcher"; Flags: ignoreversion

[Icons]
; Start Menu
Name: "{group}\{#AppName}";            Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\assets\icon.ico"
Name: "{group}\Stop {#AppName}";       Filename: "powershell.exe"; Parameters: "-ExecutionPolicy Bypass -WindowStyle Hidden -File ""{app}\launcher\stop.ps1"""; IconFilename: "{app}\assets\icon.ico"
Name: "{group}\Uninstall {#AppName}";  Filename: "{uninstallexe}"

; Desktop shortcut
Name: "{autodesktop}\{#AppName}";      Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\assets\icon.ico"; Tasks: ""

[Registry]
; Auto-start tray app on login (optional, based on task selection)
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "{#AppName}Tray"; ValueData: """{app}\{#TrayExeName}"""; Flags: uninsdeletevalue; Tasks: autostart

[Run]
; Run first_run.ps1 silently after install
Filename: "powershell.exe"; Parameters: "-ExecutionPolicy Bypass -WindowStyle Hidden -File ""{app}\launcher\first_run.ps1"""; Description: "Running first-time setup…"; Flags: runhidden waituntilterminated

; Launch the tray app (and app window) after install finishes
Filename: "{app}\{#TrayExeName}"; Description: "Launch {#AppName}"; Flags: postinstall nowait runasoriginaluser skipifsilent

[UninstallRun]
; Stop containers before uninstalling
Filename: "powershell.exe"; Parameters: "-ExecutionPolicy Bypass -WindowStyle Hidden -File ""{app}\launcher\stop.ps1"""; Flags: runhidden waituntilterminated

[Code]
// ── Docker Desktop prerequisite check ─────────────────────────────────────────
function DockerIsInstalled(): Boolean;
var
  Version: String;
begin
  Result := RegQueryStringValue(HKLM, 'SOFTWARE\Docker Inc.\Docker Desktop', 'Version', Version);
  if not Result then
    Result := RegQueryStringValue(HKCU, 'SOFTWARE\Docker Inc.\Docker Desktop', 'Version', Version);
end;

function InitializeSetup(): Boolean;
var
  Answer: Integer;
begin
  Result := True;

  if not DockerIsInstalled() then
  begin
    Answer := MsgBox(
      'NaviFix requires Docker Desktop to run.'  + #13#10 + #13#10 +
      'Docker Desktop is not detected on this machine.' + #13#10 + #13#10 +
      'Click OK to open the Docker Desktop download page, then re-run this installer after installation.' + #13#10 +
      'Click Cancel to proceed anyway (NaviFix may not work without Docker).',
      mbConfirmation, MB_OKCANCEL
    );

    if Answer = IDOK then
    begin
      ShellExec('open', 'https://www.docker.com/products/docker-desktop/', '', '', SW_SHOWNORMAL, ewNoWait, Answer);
      Result := False;   // Abort installer — user should install Docker first
    end;
    // If Cancel → allow install to continue anyway
  end;
end;

// ── Welcome page: show Docker status ─────────────────────────────────────────
procedure InitializeWizard();
begin
  if DockerIsInstalled() then
    WizardForm.WelcomeLabel2.Caption :=
      WizardForm.WelcomeLabel2.Caption + #13#10 + #13#10 +
      '✓ Docker Desktop detected.'
  else
    WizardForm.WelcomeLabel2.Caption :=
      WizardForm.WelcomeLabel2.Caption + #13#10 + #13#10 +
      '⚠  Docker Desktop not detected. Please install it before launching NaviFix.';
end;
